- name: Set Worker Node Hostname
  hosts: workers
  become: true
  become_user: root
  tasks: 
  - name: Set hostname
    ansible.builtin.hostname:
      name: worker{{lookup('ansible.utils.index_of', groups["workers"], 'eq', inventory_hostname) + 1 }}
      use: systemd