- name: Set Management Node Hostname
  hosts: mgmtnodes
  become: true
  become_user: root
  tasks: 
  - name: Set hostname
    ansible.builtin.hostname:
      name: worker{{lookup('ansible.utils.index_of', groups["mgmtnodes"], 'eq', inventory_hostname) + 1 }}
      use: systemd