- name: insert ssh key
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Add SSH key for root user
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', './.generated/temp_id_ed25519/id_ed25519.pub') }}"

