- name: Install qemu
  ansible.builtin.dnf:
    name:
      - qemu-kvm
      - qemu-img
      - virt-install
      - libvirt
      - libvirt-client
      - bridge-utils
    state: latest
  become: true
  become_user: root
- name: Enable 
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
    
