- name: insert ssh key
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Add SSH key for almalinux user
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', 'new_key.pub') }}"

