
- name: Configure management
  ansible.builtin.command:
    cmd: /opt/beegfs/sbin/beegfs-mgmtd --init
  become: true
  become_user: root
- name: start mgmtd
  ansible.builtin.systemd_service:
    name: beegfs-mgmtd
    state: started
    enabled: true
  become: true
  become_user: root