- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  become_user: root
- name: Kernel source
  ansible.builtin.dnf:
    name: "kernel-devel"
    state: latest
  become: true
  become_user: root
- name: BeeGFS Repo
  ansible.builtin.yum_repository:
    baseurl: "https://www.beegfs.io/release/beegfs_8.0/dists/rhel9"
    state: present
    gpgkey: "https://www.beegfs.io/release/beegfs_8.0/gpg/GPG-KEY-beegfs"
    gpgcheck: true
    name: "BeeGFS"
    description: "BeeGFS repo"
  become: true
  become_user: root
- name: Install packages
  ansible.builtin.dnf:
    name: 
    - beegfs-storage
    - beegfs-client
    - beegfs-utils
    - beegfs-mgmtd
    - beegfs-meta
    - beegfs-tools
    state: latest
  become: true
  become_user: root