- name: Kathleen packages
  ansible.builtin.dnf:
    name:
#      - subscription-manager-rhsm-certificates
      - hwdata
      - fonts-filesystem
      - dejavu-sans-fonts
      - langpacks-core-font-en
      - redhat-release-eula
      - redhat-release
      - setup
      - filesystem
      - basesystem
      - quota-nls
      - python3-setuptools-wheel
      - publicsuffix-list-dafsa
      - pcre2-syntax
      - ncurses-base
      - ncurses-libs
      - bash
      - zlib
      - xz-libs
      - libzstd
      - bzip2-libs
      - libcap
      - libuuid
      - popt
      - libxcrypt
      - sqlite-libs
      - libcom_err
      - libxml2
      - readline
      - alternatives
      - libcap-ng
      - audit-libs
      - libmnl
      - elfutils-libelf
      - crypto-policies
      - libnl3
      - lua-libs
      - pcre2
      - keyutils-libs
      - libunistring
      - libidn2
      - libibverbs
      - json-c
      - libffi
      - libgpg-error
      - libsepol
      - libselinux
      - libtalloc
      - lz4-libs
      - findutils
      - libsemanage
      - gdbm-libs
      - gmp
      - libattr
      - libacl
      - sed
      - shadow-utils
      - libsmartcols
      - numactl-libs
      - libtevent
      - libgcrypt
      - file-libs
      - libedit
      - libICE
      - dmidecode
      - jansson
      - ucx
      - libref_array
      - libtasn1
      - libtdb
      - libverto
      - which
      - file
      - libutempter
      - libassuan
      - librdmacm
      - libpsl
      - keyutils
      - libbpf
      - libnftnl
      - e2fsprogs-libs
      - groff-base
      - hostname
      - less
      - libXau
      - libxcb
      - diffutils
      - fuse-libs
      - libbasicobjects
      - libbrotli
      - libcollection
      - libdb
      - libdhash
      - libseccomp
      - libsigsegv
      - libyaml
      - lzo
      - nettle
      - gnutls
      - pciutils-libs
      - pcre
      - grep
      - xz
      - squashfs-tools
      - ucx-ib
      - libSM
      - libpsm2
      - acl
      - gettext-libs
      - gettext
      - tar
      - attr
      - mpfr
      - libcomps
      - libselinux-utils
      - libksba
      - libpcap
      - libnl3-cli
      - libteam
      - ethtool
      - ipset-libs
      - ipset
      - xml-common
      - libss
      - graphite2
      - libicu
      - snappy
      - libxcrypt-compat
      - libfontenc
      - libpng
      - pigz
      - systemd-rpm-macros
      - ncurses
      - psmisc
      - iproute
      - checkpolicy
      - gpm-libs
      - libX11-xcb
      - libestr
      - libfastjson
      - libmaxminddb
      - c-ares
      - cpio
      - inih
      - libcbor
      - libdaemon
      - libeconf
      - libev
      - libverto-libev
      - libibumad
      - libndp
      - libnfnetlink
      - libnetfilter_conntrack
      - iptables-libs
      - nftables
      - libnghttp2
      - libpath_utils
      - libini_config
      - libpipeline
      - libtool-ltdl
      - lmdb-libs
      - libldb
      - npth
      - oniguruma
      - jq
      - sg3_utils-libs
      - slang
      - newt
      - userspace-rcu
      - libssh-config
      - libreport-filesystem
      - dnf-data
      - kbd-misc
      - kbd-legacy
      - firewalld-filesystem
      - dhcp-common
      - coreutils-common
      - openssl-fips-provider-so
      - openssl-fips-provider
      - openssl-libs
      - coreutils
      - ca-certificates
      - systemd-libs
      - libblkid
      - libmount
      - glib2
      - dbus-libs
      - kmod
      - kmod-libs
      - util-linux-core
      - libfdisk
      - gzip
      - libevent
      - cracklib
      - openssl
      - cracklib-dicts
      - libpwquality
      - pam
      - util-linux
      - dbus
      - systemd-pam
      - systemd
      - dbus-common
      - dbus-broker
      - iputils
      - cronie-anacron
      - cronie
      - crontabs
      - grub2-common
      - openssh
      - device-mapper-libs
      - device-mapper
      - grub2-tools-minimal
      - cryptsetup-libs
      - kpartx
      - elfutils-default-yama-scope
      - elfutils-libs
      - libkcapi
      - libkcapi-hmaccalc
      - logrotate
      - virt-what
      - kbd
      - pciutils
      - gobject-introspection
      - freetype
      - harfbuzz
      - fontconfig
      - mkfontscale
      - xorg-x11-fonts-misc
      - json-glib
      - librhsm
      - procps-ng
      - perl-Digest
      - perl-Digest-MD5
      - perl-B
      - perl-FileHandle
      - perl-Data-Dumper
      - perl-libnet
      - perl-base
      - perl-URI
      - perl-AutoLoader
      - perl-Mozilla-CA
      - perl-if
      - perl-IO-Socket-IP
      - perl-Time-Local
      - perl-File-Path
      - perl-Pod-Escapes
      - perl-Text-Tabs+Wrap
      - perl-IO-Socket-SSL
      - perl-Net-SSLeay
      - perl-Class-Struct
      - perl-POSIX
      - perl-Term-ANSIColor
      - perl-IPC-Open3
      - perl-subs
      - perl-File-Temp
      - perl-Term-Cap
      - perl-Pod-Simple
      - perl-HTTP-Tiny
      - perl-Socket
      - perl-SelectSaver
      - perl-Symbol
      - perl-File-stat
      - perl-podlators
      - perl-Pod-Perldoc
      - perl-Fcntl
      - perl-Text-ParseWords
      - perl-mro
      - perl-IO
      - perl-overloading
      - perl-Pod-Usage
      - perl-Errno
      - perl-File-Basename
      - perl-Getopt-Std
      - perl-MIME-Base64
      - perl-Scalar-List-Utils
      - perl-constant
      - perl-Storable
      - perl-overload
      - perl-parent
      - perl-vars
      - perl-Getopt-Long
      - perl-Carp
      - perl-Exporter
      - perl-NDBM_File
      - perl-PathTools
      - perl-Encode
      - perl-libs
      - perl-interpreter
      - perl-DynaLoader
      - perl-TermReadKey
      - perl-Error
      - perl-File-Find
      - perl-lib
      - python3-pip-wheel
      - python-unversioned-command
      - python3
      - python3-libs
      - python3-setuptools
      - python3-dbus
      - python3-six
      - python3-dateutil
      - python3-gobject-base
      - python3-gobject-base-noarch
      - python3-iniparse
      - python3-libselinux
      - python3-idna
      - python3-pyyaml
      - python3-libsemanage
      - python3-distro
      - python3-inotify
      - python3-setools
      - python3-libcomps
      - libcap-ng-python3
      - python3-audit
      - python3-file-magic
      - python3-chardet
      - python3-decorator
      - python3-nftables
      - python3-firewall
      - python3-pysocks
      - python3-urllib3
      - python3-requests
      - python3-cloud-what
      - python3-systemd
      - teamd
      - iptables-nft
      - libarchive
      - libX11-common
      - libX11
      - libXext
      - libXrender
      - libXt
      - libXmu
      - libXi
      - libXpm
      - libXaw
      - libXtst
      - libXft
      - libXrandr
      - libXinerama
      - libXv
      - libXxf86dga
      - libXxf86vm
      - libdmx
      - libXcomposite
      - geolite2-country
      - geolite2-city
      - ipcalc
      - gawk-all-langpacks
      - gawk
      - krb5-libs
      - libtirpc
      - cyrus-sasl-lib
      - openldap
      - gnupg2
      - gpgme
      - libnfsidmap
      - libuser
      - passwd
      - usermode
      - python3-gpg
      - quota
      - gssproxy
      - libssh
      - librepo
      - elfutils-debuginfod-client
      - binutils-gold
      - binutils
      - tpm2-tss
      - systemd-udev
      - libfido2
      - openssh-clients
      - os-prober
      - grub2-tools
      - ima-evm-utils
      - python3-librepo
      - rsyslog-logrotate
      - rsyslog
      - curl
      - rpm-libs
      - rpm
      - policycoreutils
      - grubby
      - libmodulemd
      - libsolv
      - libdnf
      - python3-libdnf
      - python3-hawkey
      - libdnf-plugin-subscription-manager
      - python3-policycoreutils
      - policycoreutils-python-utils
      - rpcbind
      - rpm-plugin-systemd-inhibit
      - rpm-build-libs
      - rpm-sign-libs
      - python3-rpm
      - python3-dnf
      - python3-dnf-plugins-core
      - dnf
      - python3-subscription-manager-rhsm
      - subscription-manager
      - insights-client
      - authselect-libs
      - dhcp-client
      - initscripts-service
      - emacs-filesystem
      - audit
      - kexec-tools
      - authselect
      - rhc
      - yum
      - dnf-plugins-core
      - nfs-utils
      - crypto-policies-scripts
      - rpm-plugin-selinux
      - postfix
      - rpm-plugin-audit
      - sudo
      - s-nail
      - openssh-server
      - initscripts-rename-device
      - xorg-x11-utils
      - xorg-x11-xauth
      - firewalld
      - infiniband-diags
      - strace
      - parted
      - xfsprogs
      - ipmitool
      - chrony
      - microcode_ctl
      - net-tools
      - tmux
      - man-db
      - irqbalance
      - e2fsprogs
      - prefixdevname
      - tcsh
      - tcpdump
      - rsync
      - sg3_utils
      - iproute-tc
      - libfabric
      - ucx-rdmacm
      - wget
      - ucx-cma
      - numactl
      - bc
      - lshw
      - bzip2
      - unzip
      - libsysfs
      - lsscsi
      - tree
      - iwl100-firmware
      - iwl1000-firmware
      - iwl105-firmware
      - iwl135-firmware
      - iwl2000-firmware
      - iwl2030-firmware
      - iwl3160-firmware
      - iwl5000-firmware
      - iwl5150-firmware
      - iwl6000g2a-firmware
      - iwl6050-firmware
      - iwl7260-firmware
      - rootfiles
      - katello-ca-consumer-sat-mast01.ad.ucl.ac.uk
      - gpg-pubkey
      - gpg-pubkey
      - libgcc
      - selinux-policy
      - selinux-policy-targeted
      - vim-filesystem
      - linux-firmware-whence
      - linux-firmware
      - tzdata
      - p11-kit
      - NetworkManager-libnm
      - NetworkManager
      - libsss_idmap
      - expat
      - git-core
      - git-core-doc
      - perl-Git
      - git
      - libsss_certmap
      - libsss_nss_idmap
      - sssd-client
      - libsss_sudo
      - sssd-nfs-idmap
      - sssd-common
      - vim-common
      - xterm-resize
      - xterm
      - vim-enhanced
      - sssd-kcm
      - NetworkManager-team
      - NetworkManager-tui
      - p11-kit-trust
      - libgomp
      - libstdc++
      - vim-minimal
      - nspr
      - nss-util
      - libmpc
      - samba-common
      - perl-File-Copy
      - m4
      - polkit-libs
      - libquadmath
      - polkit
      - polkit-pkla-compat
      - javapackages-filesystem
      - libuv
      - perl-File-Compare
      - autoconf
      - cmake-rpm-macros
      - cmake-filesystem
      - perl-threads
      - dwz
      - elfutils
      - avahi-libs
      - libwbclient
      - samba-client-libs
      - samba-common-libs
      - sssd-common-pac
      - protobuf-c
      - hwloc-libs
      - cyrus-sasl-gssapi
      - sssd-krb5-common
      - tcl
      - make
      - cmake-data
      - cmake
      - sssd-krb5
      - sssd-ldap
      - adcli
      - libnetapi
      - libsmbclient
      - samba-ldb-ldap-modules
      - samba-libs
      - cups-libs
      - perl-threads-shared
      - perl-Thread-Queue
      - automake
      - libgfortran
      - cpp
      - nss-softokn-freebl
      - nss-softokn
      - nss
      - nss-sysinit
      - nss-tools
      - pmix
      - bind-license
      - llvm-libs
      - boost-regex
      - source-highlight
      - tzdata-java
      - libstdc++-devel
      - perl-macros
      - perl-locale
      - perl-version
      - qt5-srpm-macros
      - gettext-common-devel
      - gettext-devel
      - lua
      - kernel-srpm-macros
      - oddjob
      - libbabeltrace
      - perl-Fedora-VSP
      - ocaml-srpm-macros
      - fstrm
      - bind-libs
      - bind-utils
      - sssd-ad
      - openblas-srpm-macros
      - efi-srpm-macros
      - perl-srpm-macros
      - man-pages-overrides
      - lua-posix
      - copy-jdk-configs
      - libipt
      - gdb-headless
      - debugedit
      - rust-srpm-macros
      - perl-XML-Parser
      - lua-srpm-macros
      - ghc-srpm-macros
      - zstd
      - sssd-proxy
      - libkadm5
      - libipa_hbac
      - sssd-ipa
      - krb5-pkinit
      - zip
      - dbus-tools
      - lksctp-tools
      - java-1.8.0-openjdk-headless
      - libpkgconf
      - pkgconf
      - pkgconf-m4
      - pkgconf-pkg-config
      - rdma-core-devel
      - hwloc-devel
      - libxcrypt-devel
      - gcc
      - gcc-plugin-annobin
      - libquadmath-devel
      - annobin
      - zlib-devel
      - libevent-devel
      - libuuid-devel
      - info
      - ed
      - patch
      - fonts-srpm-macros
      - python-srpm-macros
      - pyproject-srpm-macros
      - rpm-build
      - go-srpm-macros
      - redhat-rpm-config
      - efivar-libs
      - pesign
      - intltool
      - patchutils
      - libpsm2-devel
      - pmix-devel
      - tcl-devel
      - gcc-gfortran
      - libtool
      - gcc-c++
      - ucx-devel
      - libfabric-devel
      - numactl-devel
      - jna
      - oddjob-mkhomedir
      - krb5-workstation
      - sssd
      - gdb
      - man-pages
      - perl-generators
      - samba-common-tools
      - expect
      - realmd
      - bison
      - flex
      - python3-pip
      - ltrace
      - diffstat
      - byacc
      - openldap-clients
      - gpg-pubkey
      - libaec
      - hdf5
      - libjwt
      - freeipmi
      - mariadb-connector-c-config
      - mariadb-connector-c
      - bash-completion
      - slurm
      - slurm-devel
      - slurm-libpmi
      - slurm-slurmd
      - glibc-common
      - glibc-gconv-extra
      - glibc-langpack-en
      - glibc
      - dracut
      - kernel-modules-core
      - kernel-core
      - kernel-modules
      - kernel-tools-libs
      - glibc-headers
      - kernel-headers
      - glibc-devel
      - kernel-tools
      - kernel
      - dracut-config-rescue
      - dracut-network
      - dracut-squash
      - nscd
      - nano
      - kmod-lustre-client
      - lustre-client
      - shadow-utils-subid
      - fuse3-libs
      - fakeroot-libs
      - fakeroot
      - apptainer
      - apptainer-suid
      - yum-utils
      - time
      - libcurl
      - libcurl-devel
      - openssl-devel
      - lbnl-nhc
      - gpg-pubkey
      - mdatp
      - fail2ban-selinux
      - fail2ban-server
      - fail2ban-firewalld
      - fail2ban-sendmail
      - fail2ban
      - munge-libs
      - munge
      - gmp-c++
      - gmp-devel
    state: latest
  become: true
  become_user: root

