- name: Delete Existing Private Key
  ansible.builtin.file:
    state: absent 
    path: /home/almalinux/.ssh/id_ed25519
- name: Delete Existing Public Key
  ansible.builtin.file:
    state: absent 
    path: /home/almalinux/.ssh/id_ed25519.pub    
- name: Generate key
  ansible.builtin.shell: ssh-keygen -q -t ed25519 -f /home/almalinux/.ssh/id_ed25519 -C "" -N ""
- name: Add to authorized_keys
  ansible.builtin.shell: cat /home/almalinux/.ssh/id_ed25519.pub >> /home/almalinux/.ssh/authorized_keys
- name: Get private keys
  ansible.builtin.fetch:
    src: /home/almalinux/.ssh/id_ed25519
    dest: ./.generated/temp_id_ed25519/
    flat: true
- name: Get public keys
  ansible.builtin.fetch:
    src: /home/almalinux/.ssh/id_ed25519.pub
    dest: ./.generated/temp_id_ed25519/
    flat: true
- name: Delete Munge Existing Key
  ansible.builtin.file:
    state: absent 
    path: /etc/munge/munge.key
  become: true
  become_user: root
- name: Generate Munge key
  ansible.builtin.shell: create-munge-key
  become: true
  become_user: root
- name: Get munge keys
  ansible.builtin.fetch:
    src: /etc/munge/munge.key
    dest: ./.generated/munge/
    flat: true
  become: true
  become_user: root
- name: Start munge
  ansible.builtin.systemd_service:
    name: munge
    state: started
    enabled: true
  become: true
  become_user: root
- name: ssh config file
  ansible.builtin.copy:
    src: files/ssh_config
    dest: /home/almalinux/.ssh/config
