- name: Elevate AlmaLinux. 9.x to 10 Beta
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install wget
    ansible.builtin.dnf:
      name: wget
      state: latest
  - name: Add ELevate NG repo
    ansible.builtin.get_url:
      url: https://repo.almalinux.org/elevate/testing/elevate-ng-el9.repo
      dest: /etc/yum.repos.d/elevate-ng-el9.repo
  - name: Get ELevate key
  ansible.builtin.get_url:
      url: https://repo.almalinux.org/elevate/RPM-GPG-KEY-ELevate
      dest: /root/RPM-GPG-KEY-ELevate
  - name: Import ELevate Key
    ansible.builtin.shell: rpm --import /root/RPM-GPG-KEY-ELevate/RPM-GPG-KEY-ELevate
  - name: Install ELevate
    ansible.builtin.dnf:
      name: 
        - leapp-upgrade
        - leapp-data-almalinux
      state: latest
  - name: ELevate Pre-Upgrade
    ansible.builtin.shell: leapp preupgrade
  - name: ELevate Upgrade
    ansible.builtin.shell: leapp upgrade
  - name: Post ELevate Reboot
    ansible.builtin.reboot: