- name: Create Certificates
  become: true
  become_user: jhrole
  hosts: all
  tasks: 
  - name: Copy TLS generation stub
    ansible.builtin.copy:
      mode: "0700"
      src: "./files/generate_certs.sh"
      dest: "/home/jhrole/generate_certs.sh"  
  - name: Create certificate
    ansible.builtin.shell: "bash /home/jhrole/generate_certs.sh {{inventory_hostname}}"
