- name: Install Jupyter
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install http proxy
    ansible.builtin.shell: npm install -g configurable-http-proxy
  - name: Copy Requirements
    ansible.builtin.copy:
      src: "files/requirements.txt"
      dest: "/root/requirements.txt"
  - name: Install Python bits
    ansible.builtin.pip:
      requirements: "/root/requirements.txt"
      state: latest
      virtualenv_python: python3.12
      virtualenv: "/opt/jupyterhub"