- name: Install Jupyter
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install http proxy
    ansible.builtin.shell: npm install -g configurable-http-proxy
  - name: Copy Requirements
    ansible.builtin.copy:
      src: "files/requirements.txt"
      dest: "/opt/requirements.txt"
  - name: Install Python bits
    ansible.builtin.pip:
      requirements: "/opt/requirements.txt"
      state: latest
      virtualenv_python: python3.12
      virtualenv: "/opt/jupyterhub"
  - name: Copy config file
    ansible.builtin.copy:
      src: "files/jupyterhub_config.py"
      dest: "/home/jhrole/jupyterhub_config.py"
      owner: jhrole
  - name: Copy wrapper
    ansible.builtin.copy:
      src: "files/start_jh.sh"
      dest: "/home/jhrole/start_jh.sh"
      owner: jhrole
      mode: "0750"
