- name: Install Python 3.12
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Install Python 3.12
    ansible.builtin.dnf:
      name:
        - python3.12
        - python3.12-devel
        - python3.12-pip
      state: latest