- name: Create users for the Jupyterhub instance.
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Add Shadowlords group
    ansible.builtin.group:
      name: shadowlords
      state: present
  - name: Add role user
    ansible.builtin.user:
      name: "jhrole"
      state: present
      groups: ["shadowlords"]
  - name: Set permissions of /etc/shadow
    ansible.builtin.file:
      path: /etc/shadow
      group: shadowlords
      mode: "0640"
  - name: Update sudoers
    ansible.builtin.blockinfile:
      dest: /etc/sudoers
      block: |
        Runas_Alias JUPYTER_USERS = jhrole, %course

        Cmnd_Alias JUPYTER_CMD = /opt/jupyterhub/bin/sudospawner

        jhrole ALL=(JUPYTER_USERS) NOPASSWD:JUPYTER_CMD
