- name: Set hostname
  ansible.builtin.hostname:
    name: workernode{{lookup('ansible.utils.index_of', groups["workers"], 'eq', inventory_hostname) + 1 }}
    use: systemd
  become: true
  become_user: root