- name: Reinstate rsync
  ansible.builtin.dnf:
    name:
    - rsync
    state: latest
  become: true
  become_user: root
- name: Remove ELevate
  ansible.builtin.dnf:
    name: 
      - leapp-upgrade
      - leapp-data-almalinux
    state: absent
  become: true
  become_user: root
- name: Remove ELevate Repo
  ansible.builtin.file:
    path: /etc/yum.repos.d/elevate-ng-el9.repo
    state: absent
  become: true
  become_user: root