#cloud-config
bootcmd:
  - [ dnf, config-manager, --set-enabled, crb ]
  - [ dnf, install, -y, epel-release ]

users:
  - name: ccspapp
    ssh_authorized_keys: 
      - ${public_key_openssh}
    groups: wheel
