- name: Copy TLS generation stub
  ansible.builtin.copy:
    mode: "0700"
    src: "files/generate_certs.sh"
    dest: "/home/almalinux/generate_certs.sh"  
  become: true
  become_user: root
- name: Create certificate
  ansible.builtin.shell: "bash /home/almalinux/generate_certs.sh {{inventory_hostname}}"
  become: true
  become_user: root
- name: Create config directory
  ansible.builtin.file:
    path: /home/almalinux/config
    state: directory
  become: true
  become_user: root
- name: Copy config file
  ansible.builtin.copy:
    src: "files/config.yaml"
    dest: /home/almalinux/config/config.yaml
  become: true
  become_user: root
- name: Create registry location
  ansible.builtin.file:
    path: /home/almalinux/registry
    state: directory
  become: true
  become_user: root
- name: Create authentication location
  ansible.builtin.file:
    path: /home/almalinux/auth
    state: directory
  become: true
  become_user: root
- name: Start pullthrough cache
  ansible.builtin.shell: 'docker run -d --restart=always --name registry-pullthrough -v /home/almalinux/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:4000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 4000:4000 -v /home/almalinux/config/config.yaml:/etc/docker/registry/config.yml -v /home/almalinux/registry:/var/lib/registry registry:2'
  become: true
  become_user: root