- name: Set up AI tools
  hosts: all
  tasks: 
  - name: Copy requirements.txt
    ansible.builtin.copy:
      src: requirements.txt
      dest: "/home/almalinux/requirements.txt"
  - name: Set up virtualenv
    ansible.builtin.pip:
      requirements: "/home/almalinux/requirements.txt"
      state: latest
      virtualenv_python: python3.12
      virtualenv: "/home/almalinux/pytorch"
