userlist1: ["course1", "course2", "course3", "course4", "course5", "course6", "course7", "course8", "course9", "course0"]
userlist2: ["course11", "course12", "course13", "course14", "course15", "course16", "course17", "course18", "course19", "course10"]
userlist3: ["course21", "course22", "course23", "course24", "course25", "course26", "course27", "course28", "course29", "course20"]
adminlist: ["admin1","admin2","admin3","admin4","admin5","admin6","admin7","admin8"]