- name: Configure Docker registry
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: Copy TLS generation stub
    ansible.builtin.copy:
      mode: "0700"
      src: "./files/generate_certs.sh"
      dest: "/home/almalinux/generate_certs.sh"  
  - name: Create certificate
    ansible.builtin.shell: "bash /home/almalinux/generate_certs.sh {{inventory_hostname}}"
  - name: Create config directory
    ansible.builtin.file:
      path: /home/almalinux/config
      state: directory
  - name: Copy config file
    ansible.builtin.copy:
      src: "./files/config.yaml"
      dest: /home/almalinux/config/config.yaml
  - name: Create registry location
    ansible.builtin.file:
      path: /home/almalinux/registry
      state: directory
  - name: Create authentication location
    ansible.builtin.file:
      path: /home/almalinux/auth
      state: directory
  - name: Create htpasswd file
    ansible.builtin.shell: "docker run --rm --entrypoint htpasswd httpd:2 -Bbn regadmin {{lookup('ansible.builtin.password', './.registrypas', length=16)}} > /home/almalinux/auth/htpasswd"
  - name: Start registry - rw
    ansible.builtin.shell: 'docker run -d --restart=always --name registry-pullthrough -v /home/almalinux/certs:/certs -e REGISTRY_HTTP_ADDR=0.0.0.0:4000 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key -p 4000:4000 -v /home/almalinux/config/config.yaml:/etc/docker/registry/config.yml -v /home/almalinux/registry:/var/lib/registry registry:2'