- name: Install quality of life tools
  ansible.builtin.dnf:
    name:
      - vim
      - tmux
      - git
      - make
      - wget
      - unzip
    state: latest
  become: true
  become_user: root
- name: Install compilers
  ansible.builtin.dnf:
    name:
    - g++
    - gfortran
    - patch
    - bzip2
    - make
    state: latest
  become: true
  become_user: root