- name: Generate shared SSH keys
  hosts: loginnode
  tasks: 
  - name: Generate key
    ansible.builtin.shell: ssh-keygen -q -t ed25519 -f /home/almalinux/.ssh/id_ed25519 -C "" -N ""
  - name: Add to authorized_keys
    ansible.builtin.shell: cat /home/almalinux/.ssh/id_ed25519.pub >> /home/almalinux/.ssh/authorized_keys
  - name: Get private keys
    ansible.builtin.fetch:
      src: /home/almalinux/.ssh/id_ed25519
      dest: ./temp_id_ed25519
  - name: Get public keys
    ansible.builtin.fetch:
      src: /home/almalinux/.ssh/id_ed25519.pub
      dest: ./temp_id_ed25519.pub