- name: Install cluster packages
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install compilers
    ansible.builtin.dnf:
      name:
      - g++
      - gfortran
      - openmpi-devel
      - openmpi
      - patch
      - bzip2
      - python3-mpi4py-openmpi
      state: latest
  - name: Install Slurm
    ansible.builtin.dnf:
      name:
      - slurm
      - slurm-slurmd
      - slurm-slurmctld
      - munge
      state: latest