- name: NFS Server Configuration
  hosts: mgmtnode
  become: true
  become_user: root
  tasks:
  - name: Install NFS packages
    ansible.builtin.dnf:
      name: "nfs-utils"
      state: latest
  - name: Make directory to export
    ansible.builtin.file:
      path: /nfs
      state: directory
  - name: Create exports file
    template:
      src: exports.j2
      dest:  /etc/exports
      mode: "0644"
  - name: Run exportfs
    ansible.builtin.shell: exportfs -a
  - name: Enable NFS server service
    ansible.builtin.service:
      name: nfs-server
      enabled: true
      state: started
