- name: Update packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true
  become_user: root
- name: Kernel source
  ansible.builtin.dnf:
    name: "kernel-devel"
    state: latest
  become: true
  become_user: root
- name: BeeGFS Repo
  ansible.builtin.yum_repository:
    baseurl: "https://www.beegfs.io/release/beegfs_8.0/dists/rhel9"
    state: present
    gpgkey: "https://www.beegfs.io/release/beegfs_8.0/gpg/GPG-KEY-beegfs"
    gpgcheck: true
    name: "BeeGFS"
    description: "BeeGFS repo"
  become: true
  become_user: root
- name: Install storage daemons
  ansible.builtin.dnf:
    name: "beegfs-storage"
    state: latest
  become: true
  become_user: root
- name: Install client tools
  ansible.builtin.dnf:
    name: "beegfs-client"
    state: latest
  become: true
  become_user: root
- name: Install utilities
  ansible.builtin.dnf:
    name: "beegfs-utils"
    state: latest
  become: true
  become_user: root
- name: Install helperd
  ansible.builtin.dnf:
    name: "beegfs-helperd"
    state: latest
  become: true
  become_user: root
- name: Install management service
  ansible.builtin.dnf:
    name: "beegfs-mgmtd"
    state: latest
  become: true
  become_user: root
- name: Install metadata service 
  ansible.builtin.dnf:
    name: "beegfs-meta"
    state: latest
  become: true
  become_user: root